### ISSUE TITLE
Bug: 在用户当日没有贴瓷砖时，瓷砖数量错误

### ISSUE THREAD

**Issue by zhaomaoniu** [Lipraty/nonebot-plugin-ghtiles#4]
## 操作系统
Windows

## Python 版本
3.11.9

## 插件版本
v0.1.2

## 适配器
nonebot-adapter-satori

## 复现方法
安装插件后，进行如下对话
```
: tile.bind zhaomaoniu
: 绑定成功，你的 Github 用户名是 zhaomaoniu
: tile
: zhaomaoniu 在 2024-04-04 贴了 4 个瓷砖
```
实际上，对话发生时，zhaomaoniu 在 2024-04-04 一个瓷砖也没贴

## 期望结果
插件能正确回复

**Comment by zhaomaoniu** [comment]
在4月5号的测试中，bug已不能正常复现

**Comment by zhaomaoniu** [comment]
又复现了，4月6号出现的是“zhaomaoniu 在 2024-04-06 贴了 6 个瓷砖”，是不是正则匹配到当日日期了

**Comment by Lipraty** [comment]
emmm 有可能，我测测

**Comment by Lipraty** [comment]
应该是修好了，我发个版
